fb_login:
  password: #your facebook passwd goes here
  username: #your facebook email goes here

paths:
  coco_segmentation_cfg:
  - ./settings/mask_rcnn_R_50_FPN_3x.yaml
  - ./settings/mask_rcnn_R_101_FPN_3x.yaml
  - ./settings/mask_rcnn_X_101_32x8d_FPN_3x.yaml
  neg: ./images/negative/
  pos: ./images/positive/
  tmp: ./images/tmp/
